### ISSUE TITLE
Creacion de: test_catalogo_peliculas

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#14]
from dominio.Pelicula import Pelicula
from servicio.catalogo_peliculas import CatalogoPeliculas as cp

**Comment by Luciano06663** [comment]
opcion = None
while opcion != 4:
    try:
        print('Opciones: ')
        print('1. Agregar Pelicula')
        print('2. Listar las peliculas')
        print('3. Eliminar catalogo de peliculas')
        print('4. Salir')
        opcion = int(input('Digite una opcion de menú (1-4): '))
    except Exception as e:
        print(f'Ocurrio un error de tipo: {e}')
        opcion = None
    else:
        print('Salimos del programa')
