### ISSUE TITLE
Creacion de la clase: pelicula

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#16]
https://github.com/CodeSystem2022/Los-Pitufos_Tercer_Semestre/commit/70a102f7133353f54582dc781fe2dc9346f260ec

**Comment by mairaggimenez** [comment]
from dominio.Pelicula import Pelicula
from servicio.Catalogo_peliculas import Catalogo_peliculas as cp

opcion = None
while opcion != 4:
    try:
        print("Opciones: ")
        print("1.Agregar Pelicula")
        print("2.Listar Catalogo")
        print("3.Eliminar Pelicula")
        print("4.Salir")
        opcion = int(input("Digite una opcion de menu (1-4): "))
        if opcion == 1:
            nombre_pelicula = input("Digite el nombre de la pelicula: ")
            pelicula = Pelicula(nombre_pelicula)
            cp.agregar_peliculas(pelicula)
        elif opcion == 2:
            cp.listar_peliculas()
        elif opcion ==3:
            cp.eliminar_peliculas()
    except Exception as e:
        print(f"Ocurrio un error de tipo: {e}")
        opcion = None
    else:
        print("Salimos del programa...")

**Comment by anacastello19** [comment]
class Pelicula:
    def __init__(self, nombre):
        self._nombre = nombre

    def __str__(self):
        return f'Pelicula: {self._nombre}'

    @property #Getter
    def nombre (self):
        return self._nombre
    @nombre.setter
    def nombre(self, nombre):
        self._nombre= nombre
