### ISSUE TITLE
Pruebas con Downcasting y Upcasting: Parte 1

### ISSUE THREAD

**Issue by EzequielgGarcia** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#25]

**Comment by Luciano06663** [comment]
public class TestConversionObjetos {
    public static void main (String[] args){
        Empleado empleado;
        empleado = new Escritor("Juan",+ 5000 , TipoEscritura.CLASICO);
        System.out.println("empleado = "+ empleado);
        //System.out.println("empleado.obtenerDetalles()");
        
        //Downcasting
        //((Escritor)empleado).getTipoEscritura();
        Escritor escritor = (Escritor) empleado;
        escritor.getTipoEscritura();
        
        //Upcasting
        Empleado empleado2 = escritor;
        System.out.println(empleado.obtenerDetalles());
