### ISSUE TITLE
Creamos la clase Object

### ISSUE THREAD

**Issue by EzequielgGarcia** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#27]

**Comment by mairaggimenez** [comment]
package test;

import domain.*;

public class Test_instanceof {
    
    public static void main(String[] args) {
        
        Empleado empleado1 = new Empleado("Matias", 26530232);
        determinarTipo(empleado1);
        empleado1 = new Gerente("Mario", 125.200, "Informatica");
        
    }
    
    public static void determinarTipo(Empleado empleado)   {
        if(empleado instanceof Gerente) { //si variable en memoria es tipo gerente
            System.out.println("Es de tipo Gerente");
            Gerente gerente = (Gerente)empleado;
            gerente.getDepartamento();
        }
        else if(empleado instanceof Empleado)   {
            System.out.println("Es de tipo Empleado");
        }
        else if(empleado instanceof Object) {
            System.out.println("Es de tipo Object");
        }
    }
    
    
}
