### ISSUE TITLE
Hashcode y equals

### ISSUE THREAD

**Issue by EzequielgGarcia** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#28]
video 4 Hashcode y equals JAVA

**Comment by mayhrina30** [comment]
Import doiman .*;
public class TestClaseobject{
public Static void main(String[] args){

Empleado empleado1 = new Empleado("Juan" , 5000);
Empleado empleado2 = new Empleado(" Juan" , 5000);

if(empleado1 == empleado2){
System.out.println("Tienen la misma referencia en memoria");
}
else{
Syste.out.println("tienen distinta referencia de memoria");

}
if(empleado1.equals(empleado2)){
System.out.println("los objetos son iguales en los contenidos");
}
else{
Sistem.out.printl("los objetos son diferentes a los contenidos
