### ISSUE TITLE
Polimorfismo Parte 2

### ISSUE THREAD

**Issue by Luciano06663** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#40]

**Comment by anacastello19** [comment]
package test;

import domain.*;

public class TestInstanceOf {

    public static void main(String[] args) {
        //Objeto tipo gerente
        Empleado empleado1 = new Empleado("Juam", 2000);
        determinarTipo(empleado1);
        empleado1 = new Gerente("Pablo", 2000, "System");
    }

    public static void determinarTipo(Empleado empleado) {
        if (empleado instanceof Gerente) {
            System.out.println("Es de tipo Gerente");
            //Dos formas para convertir una clase padre a hija
            Gerente gerente = (Gerente) empleado;
            ((Gerente) empleado).getDepartamento();
            System.out.println("gerente = " + empleado);
        } else if (empleado instanceof Empleado) {
            System.out.println("Es de tipo empleado");
//            Gerente gerente = (Gerente) empleado;
//            System.out.println("gerente = " + gerente.getDepartamento());
        } else if (empleado instanceof Object) {
            System.out.println("Es de tipo Object");
        }
    }
}
