### ISSUE TITLE
Polimorfismo paso a paso

### ISSUE THREAD

**Issue by Luciano06663** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#42]
paso a paso poliforsismo

**Comment by mayhrina30** [comment]
/////////////////////////PARTE 1//////////////////////
package test;

import domain.*;
public class TestSobreEscritura {
    public static void main(String[] args) {
        
        Empleado empleado1 = new Empleado("Juan" , 10000);
        
        imprimir(empleado1);
        System.out.println("empleado1 = " + empleado1.obtenerDetalles());
        Gerente gerente1 = new Gerente("Jose ", 5000 , " Sistemas");
        
        imprimir (gerente1);
        System.out.println("gerente1 = " + gerente1.obtenerDetalles());
        
    }
    public static void imprimir(Empleado empleado){
        System.out.println("empleado =" + empleado.obtenerDetalles());
    }
    
}

**Comment by mayhrina30** [comment]
////////////////////////PARTE 2///////////////
package test;

import domain.*;
public class TestSobreEscritura {
    public static void main(String[] args) {
        
        Empleado empleado1 = new Empleado("Juan" , 10000);
        
        imprimir(empleado1);
        //System.out.println("empleado1 = " + empleado1.obtenerDetalles());
        Empleado1  = new Gerente("Jose ", 5000 , " Sistemas");
        
        imprimir (empleado1);
        //System.out.println("gerente1 = " + gerente1.obtenerDetalles());
        
    }
    public static void imprimir(Empleado empleado){
        System.out.println("empleado =" + empleado.obtenerDetalles());
    }
    
}
