### ISSUE TITLE
Sintaxis de Clases en JavaScript

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#43]

**Comment by mairaggimenez** [comment]
//let persona3 = new Persona("Carla", "Roma");

class Persona   {
    constructor(nombre, apellido)   {
        this._nombre = nombre;
        this._apellido = apellido;
    }

    get nombre()    {
        return this._nombre;
    }

    set nombre(nombre) {
        this._nombre = nombre;
    }

    get apellido()  {
        return this._apellido;
    }

    set apellido(apellido) {
        return this_apellido = apellido;
    }

}

class Empleado extends Persona  {
        constructor(nombre,apellido,departamento) {
            super(nombre,apellido);
            this._departamento = departamento;
        }

        get departamento()  {
            return this._departamento;
        }

        set departamento(departamento)  {
            this._departamento = departamento;
        }
}



let persona1 = new Persona("Juan", "Romera");
//console.log(persona1);
console.log(persona1.nombre);
persona1.nombre = "Juan Carlos";
console.log(persona1.nombre);
let persona2 = new Persona("Ana", "Sosa");
//console.log(persona2);
console.log(persona2.nombre);
persona2.nombre = "Paola";
console.log(persona2.nombre);

let empleado1 = new Empleado("Jose","Pipo","Informatica");
console.log(empleado1);

**Comment by mayhrina30** [comment]
///////////Parte 2//////
class Persona{

  constructor(nombre , apellido{
this.nombre = nombre;
this.apellido = apellido;
}
}

let persona1 = new Perona(' Martin' , 'Perez');
console.log(persona1);
let persona2 = new Peroana('Carlos' , 'Lara'),
console.log(persona2);
