### ISSUE TITLE
hoisting y clases

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#45]

**Comment by jorolio** [comment]
Cuando trabajamos con clases no se aplica el concepto de hosting. primero debe definirse para poder utilizarce. si trabajamos con funciones podemos primero llamar la función y luego definirla ya que se aplica el concepto hosting. entonces, hosting no se puede realizar con las clases pero si con las funciones.

**Comment by jorolio** [comment]
//let persona3 = new Persona('Carla', 'Ponce');

class Persona{
    constructor(nombre, apellido){
        this._nombre;
        this._apellido;
    }

    get nombre(){
        return this._nombre;
    }

    set nombre(nombre){
        this._nombre = nombre;
    }

    get apellido(){
        return this._apellido;
    }

    set apellido(apellido){
        this._apellido = apellido;
    }
}

let persona1 = new Persona('Martin', 'Perez');
console.log(persona1.nombre);
persona1.nombre = 'Juan Carlos';
console.log(persona1.nombre);
//console.log(persona1);
let persona2 = new Persona('Carlos', 'Lara');
console.log(persona2.nombre);
persona2._nombre = 'Maria Laura';
console.log(persona2.nombre);
//console.log(persona2);
