### ISSUE TITLE
Palabra Static con metodos Parte 1

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#55]
Subir el código perteneciente al video 1, de la semana 8 de JavaScript

**Comment by mairaggimenez** [comment]
//let persona3 = new Persona("Carla", "Roma");

class Persona   {

    static contadorPersonas = 5; //Atributo estatico
    //email = "Valor default emails"; //Atributo no estatico

    static get MAX_OBJ()    { //metodo que simula constante
        return 5;
    }

    constructor(nombre, apellido)   {
        this._nombre = nombre;
        this._apellido = apellido;
        if(Persona.contadorPersonas < Persona.MAX_OBJ)  {
            this.idPersona = ++Persona.contadorPersonas;
        }
        else {
            console.log("Se ha superado max obj permitidos");
        }
        this.idPersona = Persona.contadorPersonas;
        //console.log("Se incrementa el contador:" + Persona.contadorObjetosPersona)
    }

    get nombre()    {
        return this._nombre;
    }

    set nombre(nombre) {
        this._nombre = nombre;
    }

    get apellido()  {
        return this._apellido;
    }

    set apellido(apellido) {
        return this_apellido = apellido;
    }

    nombreCompleto()  {
        return this.idPersona + " " + this._nombre + " " + this._apellido;
    }

    toString() { //regresa un string
        return this.nombreCompleto();
    }

    static saludar()    {
        console.log("Saludos desde Marte Satic");
    }

    static saludar2() {
        console.log(persona1.nombre + " " + persona1._apellido);
    }

}

class Empleado extends Persona  {
    constructor(nombre,apellido,departamento) {
        super(nombre,apellido);
         this._departamento = departamento;
    }

    get departamento()  {
        return this._departamento;
    }

    set departamento(departamento)  {
        this._departamento = departamento;
    }

    //sobreescritura modificar comportamiento de metodo en clase padre

    nombreCompleto()    {
        return super.nombreCompleto() + ", " + this._departamento;
    }

    //sobreescribiendo tooStrting clase padre
    tooString() { 
        //se aplica polimorfismo = multiples
        //formas en tiempo de ejecucion
        return this.nombreCompleto();
    }
}



let persona1 = new Persona("Juan", "Romera");
//console.log(persona1);
console.log(persona1.nombre);
persona1.nombre = "Juan Carlos";
console.log(persona1.nombre);
let persona2 = new Persona("Ana", "Sosa");
//console.log(persona2);
console.log(persona2.nombre);
persona2.nombre = "Paola";
console.log(persona2.nombre);

let empleado1 = new Empleado("Jose","Pipo","Informatica");
console.log(empleado1);
console.log(empleado1.nombreCompleto());

//object.prototype.toString _Esta es la manera de acceder a atribuot y metodos
//de manera dinamica
console.log(empleado1.toString());
console.log(persona1.toString()); 

//No se utiliza desde el objeto
//persona1.saludar();

Persona.saludar();
Persona.saludar2();

Empleado.saludar();
Empleado.saludar2();

//console.log(persona1.contadorObjetosPersona);
console.log(Persona.contadorObjetosPersona);
console.log(Empleado.contadorObjetosPersona);

console.log(persona1.email);
console.log(empleado1.email);
//console.log(Persona.email);

console.log(persona1.toString());
console.log(empleado1.toString());
console.log(Persona.contadorPersonas);

let persona3 = new Persona ("Carla", "Pertosi");
console.log(persona3.toString());
console.log(Persona.contadorPersonas);

console.log(Persona.MAX_OBJ);
//Persona.MAX_OBJ = 10; No se puede modifica

console.log(Persona.MAX_OBJ);

let persona4 = new Persona("Franco", "Dias");
console.log(persona4.toString());

**Comment by mairaggimenez** [comment]
AHI TA CODIGO LU...! GRAX
