### ISSUE TITLE
Atributos estaticos 

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#57]
Subir el código perteneciente al video 3, de la semana 8 de JavaScript

**Comment by santimanas** [comment]
class Persona{
    static contadorObjetosPersona = 0;

    constructor(nombre, apellido){
        this._nombre = nombre;
        this._apellido = apellido;
        Persona.contadorObjetosPersona++;
        console.log("Se incrementa el contador: "+Persona.contadorObjetosPersona);
    }

}

console.log(Persona.contadorObjetosPersona); 0
console.log(Empleado.contadorObjetosPersona); 0
