### ISSUE TITLE
Uso de la palabra static Parte 1

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#59]
Subir el código perteneciente al video 5, de la semana 8 de JavaScript

**Comment by EzequielgGarcia** [comment]
//Uso de la palabra static: Parte 1 
   //Esta es la manera de acceder a atributos y métodos de manera dinámica 
      console.log(persona1.toString()) 
      console.log(persona2.toString()) 
      console.log(empleado1.toString())
      console.log(Persona.contadorPersonas) 

const persona3 = new Persona('Flavio', 'Rodriguez')
    console.log(`persona3: ${persona3.toString()}`) 
    console.log(Persona.contadorPersonas) 

//Función de persona
function Persona3(nombre, apellido, email){
    this.nombre = nombre;
    this.apellido = apellido;
    this.email = email;
    this.nombreCompleto = function(){
        return this.nombre + " " + this.apellido;
    }
}
let padre = new Persona3('Flavio', 'Rodriguez','Flavio@gmail.com');
padre.nombre ='Luis'; 
console.log(padre);
console.log(padre.nombreCompleto()); 
let madre = new Persona3('Roberto','Carlos','Carlos@gmail.com');
console.log(madre);
console.log(madre.nombreCompleto());
