### ISSUE TITLE
Creación de constantes estaticas

### ISSUE THREAD

**Issue by LucianaBaigorria** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#61]
Subir el código perteneciente al video 7, de la semana 8 de JavaScript

**Comment by mayhrina30** [comment]
empezamos

**Comment by mayhrina30** [comment]
//let persona3 = new persona('carla' , 'ponce'); ESTO NI DEBE ASERSE
class Persona{
static contadorPersona = 0; //atributo statico
//email = 'valor default email' // atributo no estatico

static get MAX_OBJ(){ //este metodo simula una constante
    return 5;
}

    constructor(nombre , apellido){
        this.nombre = nombre;
        this.apellido = apellido;

    }
    get nombre(){
        return this._nombre;
    }
    set nombre(nombre){
        this._nombre = nombre;
    }
    get apelido(){
        return this._apellido;

    }
    get apellido(){
        return this._apellido
    }
    set apellido(apellido){
        return this._apellido;
    }
    nombreCompleto(){
        return this,this._nombre+' '+this._apellido;

    }
    tostring(){ // regresa un string
        return this.nombreCompleto
    }
    static saludar(){
        console.log('saludos desde este metodo');
    }
    static saludar2(persona){
        console.log(persona.nombreCompleto);

    }
}

 class Empleado extends persona{ // clase hija
    construcctor( nombre ,apellido ,departemento){
        super(nombre, apellido);
        this._departamento = departemento

    }
    get departamento(){
        return this._departamento;

    }
    set departemneto(departamento){
        return this._departamento = departamneto;

    }
            //Sobreescritura
    nombreCompleto(){
        this.nombreCompleto()
        return this.nombre+' '+this._apellido+' '+this._departameto;
    
}
    //sobreescribiendo el metodo de la clase del padre
    // se aplica en polimorfismo que  significa = multiples formas en tiempo de 
    // el metodo que se ejecuta depende se es una referncia de tipo padre o hija
    toString(){
        return this.nombreCompleto();

    }

}

let Persona1 = Persona('Martin' , 'Perez');
//console.log(persona1); 
console.log(persona1.nombre);
persona1.nombre =' juan carlos';
console.log(persona1.nombre);
let persona2= new Persona('carlos' , 'lara' );
console.log(persona2.nombre);
persona2.nombre = 'Maria laura';
console.log(persona2.nombre);
//console.log(persona2);


 //let empleado1 = new Empleado('Maria','Gimenez', 'sistemas');
 //console.log(empleado1);
 //console.log(Empleado1.nombreCompleto());
 //console.log( empleado1.toString());
 //console.log(persona1.tostring());

 persona1.saludar();
 persona.saludar2(persona1);

let persona2 = new Persona("Ana", "Sosa");
//console.log(persona2);
console.log(persona2.nombre);
persona2.nombre = "Paola";
console.log(persona2.nombre);

let empleado1 = new Empleado("Jose","Pipo","Informatica");
console.log(empleado1);
console.log(empleado1.nombreCompleto());

//object.prototype.toString _Esta es la manera de acceder a atribuot y metodos
//de manera dinamica
console.log(empleado1.toString());
console.log(persona1.toString());

//No se utiliza desde el objeto
//persona1.saludar();

Persona.saludar();
Persona.saludar2();

Empleado.saludar();
Empleado.saludar2();

//console.log(persona1.contadorObjetosPersona);
console.log(Persona.contadorObjetosPersona);
console.log(Empleado.contadorObjetosPersona);

console.log(persona1.email);
console.log(empleado1.email);
//console.log(Persona.email);

console.log(persona1.toString());
console.log(empleado1.toString());
console.log(Persona.contadorPersonas);

let persona3 = new Persona ("Carla", "Pertosi");
console.log(persona3.toString());
console.log(Persona.contadorPersonas);

console.log(Persona.MAX_OBJ);
//Persona.MAX_OBJ = 10; No se puede modifica

console.log(Persona.MAX_OBJ);

let persona4 = new Persona("Franco", "Dias");
console.log(persona4.toString());
