### ISSUE TITLE
Manejo de loggin: Parte 1

### ISSUE THREAD

**Issue by santimanas** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#63]

**Comment by santimanas** [comment]
import logging as log

if name == "main":
log.basicConfig(level=log.DEBUG)
log.debug("Mensaje a nivel debug")
log.info("Mensaje a nivel info")
log.warning("mensaje a nivel warning")
log.error("mensaje a nivel error")
log.critical("mensaje a nivel critical")

**Comment by EzequielgGarcia** [comment]
import logging
logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)
logging.debug('This message should go to the log file')
logging.info('So should this')
logging.warning('And this, too')
logging.error('And non-ASCII stuff, too, like Øresund and Malmö')

**Comment by Luciano06663** [comment]
# Miaplicaion.py
import logging
import mylib

def main():
    logging.basicConfig(filename='myapp.log', level=logging.INFO)
    logging.info('Started')
    mylib.do_something()
    logging.info('Finished')

if __name__ == '__main__':
    main()
# mylib.py
import logging

def do_something():
    logging.info('Doing something')
