### ISSUE TITLE
Metodo de seleccionar (video2)

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#66]

**Comment by EzequielgGarcia** [comment]
class perosnaDAO:
   """
  DAO significa: Data Access Object
  CRUD significa: 
                          Create -> Insertar
                          Read   -> Seleccionar
                          Update -> Actalizar
                          Delete -> Eliminar
 """
_SELECCIONAR = 'SELECT' * FROM persona ORDER BY id_persona'
_INSERTAR = 'INSERT INTO persona(nombre, apellido email) VALUES (%s,%s,%s)
_ACTUALIZAR = 'ULDATE persona SET nombre=%s, apellido%s, email=%s WHERE id_persona%s'
_ELIMINAR = 'DELETE FROM persona WHERE id_persona=%s'

# Definimos los métodos de clase 
@classmethod
def seleccionar(cls):
     with Conexion.obtenerConexion():
         with Conexion.obtenerCursor() as cursor:
               cursor.execute(cls._SELECCIONAR)
               registro = cursor.fetchall()
               personas = [] # Creamos una lista
               for registro in registros:
                   persona = Persona(registro[0], registro[1], registro[2], registro[3])
                   personas. append( persona)
    

if __name__ == '__main__':
    personas = PersonasDAO.seleccionar()
    for personas in personas:
         log.debug(persona)
