### ISSUE TITLE
metodo insertar

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#67]

**Comment by Luciano06663** [comment]
def insertar(cls, persona):
	with Conexion.obtenerConexion():
		with Conexion.obtenerCursor() as cursor:
		valores = (persona.nombre, persona.apellido, persona.email)
		cursor.execute(cls. INSERTAR, valores)
		log.debug(f'Persona Insertada: {persona}')
		return cursor.rowcount



if __ name__ == '__main__':
	#Insertar un registro
	personal = Persona(nombre="Pedro"', apellido="'Romero"', email="'promerogmail.com')
	personas_insertadas = PersonaDA0.insertar(persona1)
	log.debug(f Personas insertadas: (personas insertadas)')
	# Seleccionar objetos
	personas = PersonaDAO.seleccionar()
	for persona in personas:
	log.debug(persona)
