### ISSUE TITLE
metodo actualizar

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#68]

**Comment by jorolio** [comment]
@classmethod
    def actualizar(cls, persona):
        with Conexion.obtenerConexion():
            with Conexion.obtenerCursor() as cursor:
                valores = (persona.nombre, persona.apellido, persona.email, persona.id_persona)
                cursor.execute(cls._ACTUALIZAR, valores)
                log.debug(f'Persona actualizada: {persona}')
                return cursor.rowcount
