### ISSUE TITLE
metodo eliminar

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#69]

**Comment by santimanas** [comment]
@clasmethod
    def eliminar(cls, persona):
        with Conexion.ObtenerConexion():
            with Conexion.ObtenerCursor() as cursor:
                valores: (persona.id_persosa, )
                cursor.executed(cls._ELIMINAR, valores)
                log.debug(f'Los objetos eliminados son: {persona}')
                return cursor.rowcount
