### ISSUE TITLE
haciendo pruebas y eliminando errores

### ISSUE THREAD

**Issue by mayhrina30** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#70]

**Comment by mairaggimenez** [comment]
from Capa_datos_persona.Conexion import Conexion
from Capa_datos_persona.Persona import Persona
from Loger_base import log


class PersonaDao:
    """
    DAO: data access object
    CRUD:
    -Create:Insertar
    -Read:Seleccionar
    -Update:Actualizar
    Dlete:Eliminar
    """
    _SELECCIONAR = "SELECT * FROM paersona ORDER BY id_persona"
    _INSERTAR = "INSERT INTO persona(nombre,apellido,email) VALUES (%s,%s,%s)"
    _ACTUALIZAR = "UPDATE persona SET nombre=%s,apellido=%s,email=%s WHERE id_persona=%s"
    _ELIMINAR = "DELETE FROM persona WHERE id_persona=%s"

    @classmethod
    def seleccionar(cls,persona):
        with Conexion.obtenerConexion():
            with Conexion.obtenerCursor() as cursor:
                cursor.execute(cls._SELECCIONAR)
                registros = cursor.fetchall()
                personas = []
                for registro in registros:
                    persona = Persona (registro[0], registro[1], registro[2], registro[3])
                    personas.append(persona)
                return personas

    @classmethod
    def insertar(cls,persona):
        with Conexion.obtenerConexion():
            with Conexion.obtenerConexion() as cursor:
                valores = (persona.nombre, persona.apellido, persona.email)
                cursor.execute(cls._INSERTAR)
                log.debug(f"Persona Insertada: {persona}")
                return cursor.rowcount

    @classmethod
    def actualizar(cls,persona):
        with Conexion.obtenerConexion():
            with Conexion.obtenerConexion() as cursor:
                valores = (persona.nombre, persona.apellido, persona.email, persona.id_persona)
                cursor.execute(cls._ACTUALIZAR)
                log.debug(f"Persona actualizada: {persona}")
                return cursor.rowcount

    @classmethod
    def eliminar(cls,persona):
        with Conexion.obtenerConexion():
            with Conexion.obtenerConexion() as cursor:
                valores= (persona.id_persona,)
                cursor.execute(cls._ELIMINAR)
                log.debug(f"Personas eliminadas: {persona}")
                return cursor.rowcount

if __name__ == "__main__":
    #eliminar registro
    persona1 = Persona(id_persona=2)
    personas_eliminadas = PersonaDao.eliminar(persona1)
    log.debug(f"Persona eliminada: {personas_eliminadas}")
    #actualizar registro
    persona1 = Persona(1, "Mario", "Gimenez", "MG@yahoo.com")
    personas_actualizadas = PersonaDao.actualizar(persona)
    log.debug(f"Personas actualizadas: {personas_actualizadas}")
    #insertar un registro
    persona1 = Persona(nombre="Pedro",apellido="Romero",email="Promero@gmail.com")
    personas_insertadas = PersonaDao.insertar(persona1)
    log.debug(f"Personas insertadas: {personas_insertadas}")
    #seleccionar objetos
    personas = PersonaDao.seleccionar()
    for persona in personas:
        log.debug(persona)

**Comment by mairaggimenez** [comment]
Terminando.......
