### ISSUE TITLE
Clase Conexion 1 y 2

### ISSUE THREAD

**Issue by santimanas** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#71]

**Comment by santimanas** [comment]
Parte 1

import java.sql.Connection;

public class Conexion {
    public static Connection getConection(){
        Connection conexion = null;
        var baseDatos = "estudiantes2022";
        var url = "jdbc:mysql://localhost:3405/"+baseDatos;
        var usuario = "root";
        var password = "admin";
     
        Class.forName("com.mysql.cj.jdbc.Driver");
        conexion = DriverManager.getConnection(url, usuario, password);
        
    }
               
}

**Comment by EzequielgGarcia** [comment]
parte 2

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLExepcion;

try {
      class.forName("com.mysql.cj.jdbc.Drive");
      conexion = DriverManager.getConnection(url, usuario, password);
} catch (ClassNotFoundException | SQLException e){
      system.out.println("ocurrió un error en la conexión: "+e.getMessage());
}//Fin catch
return conexion;

**Comment by jorolio** [comment]
Main.java

package UTN;

import UTN.conexion.Conexion;

public class Main {
    public static void main(String[] args) {
        var conexion = Conexion.getConnection();
        if (conexion != null){
            System.out.println("Conexion exitosa: "+conexion);
            else
            System.out.println("Error al conectarse");
        } //Fin main
    } // Fin clase
