### ISSUE TITLE
Pruebas de personaDAO -> Parte 1

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#76]

**Comment by jorolio** [comment]
#Insertar un registro
    persona1 = Persona(nombre='Marcos', apellido='Tejada', email='tejadam@mail.com')
    personas_insertadas = PersonaDAO.insertar(persona1)
    log.debug(f'Personas insertadas: {personas_insertadas}')
