### ISSUE TITLE
Creamos la Clase CursorDelPool -> Parte 1

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#77]

**Comment by mairaggimenez** [comment]
from logger_base import log
from conexion import Conexion
class cursorDelPool:
    def __init__(self):
        self._conexion = None
        self._cursor = None
        
    def __enter__(self):
        log.debug("Inicio metodo with y __enter")
        self._conexion = Conexion.obtenerConexion()
        self._cursor = self._conexion.cursor()
        return self._cursor
