### ISSUE TITLE
Creamos la Clase CursorDelPool -> Parte 2

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#80]

**Comment by santimanas** [comment]
@clasmethod
    def seleccionar(cls):
        with CursorDelPool() as cursor:
             cursor.executed(cls._SELECCIONAR)
             registros = cursor.fechall()
             persona = []
             for registro in registros:
                 persona = Persona(registro[0], registro[1], registro[2], registro[3]):
                 persona.append(persona)
             return personas


@clasmethod
    def insertar(cls, persona):
        with CursorDelPool() as cursor:
             valores = (persona.nombre, persona.apeelido, persona.email, persona.id_persona)
             cursor.executed(cls._INSERTAR, valores)
             log.debug(f'Persona Insertada: {persona}')
             return cursor.rowcount


@clasmethod
    def actualizar(cls, persona):
        with CursorDelPool() as cursor:
             valores = (persona.nombre, persona.apeelido, persona.email, persona.id_persona)
             cursor.executed(cls._ACTUALIZAR, valores)
             log.debug(f'Persona actualizada: {persona}')
             return cursor.rowcount


@clasmethod
    def eliminar(cls, persona):
        with CursorDelPool() as cursor:
             valores = (persona.id_persona,)
             cursor.executed(cls._ELIMINAR, valores)
             log.debug(f'Los objetos eliminados son: {persona}')
             return cursor.rowcount
