### ISSUE TITLE
Pruebas del CursorDelPool -> Parte 2

### ISSUE THREAD

**Issue by anacastello19** [CodeSystem2022/Los-Pitufos_Tercer_Semestre#81]

**Comment by EzequielgGarcia** [comment]
def seleccionar(cls):
     with CursorDelPool() as cursor:
     cursor.execute(cls._SELECCIONAR)
     registros = cursor.fetchall()
     personas = [] 
     for registro in registros:
          persona = Persona(registro[0]), registro[1], registro[2], registro[3] 
          personas.append(persona)
    return persona

def insertar(cls, persona):
    with CursorDelPool() as cursor:
          valores = (personas.nombre, personas,apellido, personas.email)
          cursor.execute(cls._INSERTAR, valores)
          log.debug(f'Persona Insertada: {persona}')
       return cursor.rowcount

def actualizar(cls, persona):
   with CursorDelPool() as cursor:
        valores = (persona.nombre, persona.apellido, persona.email, persona.id_persona, )
        cursor.execute()cls._ACTUALIZAR, valores)
        log.debug(f'Personas actualizada: {persona}')
        return cursor.rowcount      

def eliminar(cls, persona):
    with CursorDelPool() as cursor:
        valores= (persona.id_persona,)
        cursor.execute(cls._ELIMINAR, valores)
        log.debug(f'Los objetos eliminados son: {persona}')
        return cursor.rowcount
